### ISSUE TITLE
Umbrella: Release v1.0.0

### ISSUE THREAD

**Issue by metsavaht** [thorgate/tg-spa-utils#10]
Todo items for initial full release

- [ ] Documentation
- [ ] Tests
- [x] Memoization `@thorgate/spa-entities` selectors
- [ ] Immutable support for `@thorgate/spa-entities` - This means better performance overall
- [ ] Better control for `@thorgate/spa-pending-data`
- [x] Strictly typed action-types for resource saga action helpers
- [ ] Add package split caching option
